scrolls:
  - init-setup
  - install-devtools

hosts:
  - host: "116.202.26.176"
    pubkey_path: "/home/lukasmetzner/.ssh/id_ed25519.pub"
    privkey_path: "/home/lukasmetzner/.ssh/id_ed25519"
    user: "root"
